### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Foxeur29** [Bakalexis/uni-craft.public#2]
**Décrire le bug
C’est quand je me connecte parfois je dois redémarrer mon mc 4 a 5 fois pour me connecter au serveur et le bug me met quand il y a trop de monde je pense

**Comment le reproduire**
1.lancer le jeu
2. sa arrive quand il y a beaucoup de monde sur le serveur et je n arrive pas a me connecter sur le serveur
3. Problème de connection au serveur minecraft

**Que devrait-il se passer ?**
il met un message d erreur et refuse la connection au serveur
j’en ai pas desoler

**Serveur sur lequel le bug est rencontré**
 -connection au serveur uni-craft

**Autre chose à ajouter ?**
Vous pouvez ajouter des commentaires

**Comment by Bakalexis** [comment]
Il faut actualiser la liste des serveurs pour pouvoir se connecter
