### ISSUE TITLE
Bug Kb/Reach

### ISSUE THREAD

**Issue by BambouReloaded** [Bakalexis/uni-craft.public#8]
Bonjour,Bonsoir, petit bug en practice : Quand on saute et qu'on tape en permanance, on prends les kb en avant et la reach a l'air augmentée... C'est un bug ou c'est normal ? Car j'ai peur de me faire bannir en utilisant cette technique...

**Comment by Bakalexis** [comment]
Ceci est totalement normal, Minecraft est fait ainsi.
